/**
 * MIME types
 *
 * @see {@link https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Basico_sobre_HTTP/MIME_types}
 */
export enum MimeTypesEnum {
  AtomXml = 'application/atom+xml',
  AtomcatXml = 'application/atomcat+xml',
  Bmp = 'image/bmp',
  Css = 'text/css',
  Csv = 'text/csv',
  Ecmascript = 'application/ecmascript',
  Gif = 'image/gif',
  H264 = 'video/h264',
  Html = 'text/html',
  JavaArchive = 'application/java-archive',
  Javascript = 'application/javascript',
  Jpeg = 'image/jpeg',
  Json = 'application/json',
  Midi = 'audio/midi',
  Mp4Application = 'application/mp4',
  Mp4Audio = 'audio/mp4',
  Mp4Video = 'video/mp4',
  MpegAudio = 'audio/mpeg',
  MpegVideo = 'video/mpeg',
  OctetStream = 'application/octet-stream',
  OggAudio = 'audio/ogg',
  OggVideo = 'video/ogg',
  Pdf = 'application/pdf',
  Pkcs10 = 'application/pkcs10',
  Pkcs7Mime = 'application/pkcs7-mime',
  Pkcs7Signature = 'application/pkcs7-signature',
  Pkcs8 = 'application/pkcs8',
  Plain = 'text/plain',
  Png = 'image/png',
  Postscript = 'application/postscript',
  Quicktime = 'video/quicktime',
  RdfXml = 'application/rdf+xml',
  RichText = 'text/richtext',
  RssXml = 'application/rss+xml',
  Rtf = 'application/rtf',
  Sgml = 'text/sgml',
  SmilXml = 'application/smil+xml',
  SvgXml = 'image/svg+xml',
  Threegpp = 'video/3gpp',
  Tiff = 'image/tiff',
  WebmAudio = 'audio/webm',
  WebmVideo = 'video/webm',
  Webp = 'image/webp',
  XAac = 'audio/x-aac',
  XAiff = 'audio/x-aiff',
  XFontOtf = 'application/x-font-otf',
  XFontTtf = 'application/x-font-ttf',
  XFontWoff = 'application/x-font-woff',
  XMpegurl = 'audio/x-mpegurl',
  XMsWma = 'audio/x-ms-wma',
  XPkcs12 = 'application/x-pkcs12',
  XShockwaveFlash = 'application/x-shockwave-flash',
  XSilverlightApp = 'application/x-silverlight-app',
  XWav = 'audio/x-wav',
  XhtmlXml = 'application/xhtml+xml',
  Xml = 'application/xml',
  XmlDtd = 'application/xml-dtd',
  XsltXml = 'application/xslt+xml',
  Yaml = 'text/yaml',
  Zip = 'application/zip',
}
